apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
  annotations:
    # service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    # prometheus.io/scrape: "true"
    # prometheus.io/path: "_status/vars"
    # prometheus.io/port: "8080"
spec:
  ports:
  - name: tcp
    port: 26257
    targetPort: 26257
  - name: http
    port: 8080
    targetPort: 8080
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: cockroachdb